### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by skrat** [arximboldi/ewig#18]
OS: Arch Linux

Followed the step on arch wiki to install and bootstrap nix. Followed your build steps in the README, got loads of compilation errors. This is not exactly a replicable build. I thought everything is pinned and there's no way for this to fail. Which is too bad, I was looking forward to exploring the architecture. Cmake + git submodules for deps would be much simpler in the end, wouldn't it?

Edit: libhttpserver seems to be the culprit. Also weird in your deps.nix is two versions of GCC used. When I leave that alone and use both gcc5 and gcc7, I get this:

```
...
-- Found libhttpserver: /nix/store/cvfx5r98hn19h4ifwvr84wcr6jywjrbk-libhttpserver-git-4895f43ed29195af70beb47bcfd1ef3ab4555665/include, /nix/store/cvfx5r98hn19h4ifwvr84wcr6jywjrbk-libhttpserver-git-4895f43ed29195af70beb47bcfd1ef3ab4555665/lib/libhttpserver.so
-- Configuring done
CMake Warning at CMakeLists.txt:50 (add_executable):
  Cannot generate a safe runtime search path for target ewig-debug because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libncursesw.so.6] in /nix/store/mi5krns5p204a3rdn1rj4ajnbqn2809i-ncurses-6.1-20181027/lib may be hidden by files in:
      /usr/lib64
    runtime library [libformw.so.6] in /nix/store/mi5krns5p204a3rdn1rj4ajnbqn2809i-ncurses-6.1-20181027/lib may be hidden by files in:
      /usr/lib64

  Some of these libraries may not be found correctly.


CMake Warning at CMakeLists.txt:45 (add_executable):
  Cannot generate a safe runtime search path for target ewig because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libncursesw.so.6] in /nix/store/mi5krns5p204a3rdn1rj4ajnbqn2809i-ncurses-6.1-20181027/lib may be hidden by files in:
      /usr/lib64
    runtime library [libformw.so.6] in /nix/store/mi5krns5p204a3rdn1rj4ajnbqn2809i-ncurses-6.1-20181027/lib may be hidden by files in:
      /usr/lib64

  Some of these libraries may not be found correctly.


-- Generating done
-- Build files have been written to: /home/skrat/Downloads/ewig/build

```

**Comment by arximboldi** [comment]
Hi!

It seems CMake is getting confused because of stuff in your native system, outside of Nix. You can probably get rid of that warning if you use `nix-shell --pure` instead.

In any case, it seems that, in spite of the warning, CMake did indeed generate a Makefile. Have you tried running `make` after?

> Also weird in your deps.nix is two versions of GCC used

Sadly due to a bug in `libhttpserver` an older gcc had to be used. I think it has been fixed by now, I am using a newer version in other projects. I may some day sit down and update the `deps.nix` for this project :slightly_smiling_face:

**Comment by Saldivarcher** [comment]
@arximboldi running `make` after running `nix-shell` failed for myself, but using `nix-shell --pure` instead allowed me to build. Thanks for that suggestion :)

**Comment by skrat** [comment]
@arximboldi I gave up, I tried running examples and using `ewig` and then on its own `lager`, but sorry, the whole experience is frustrating and broken. IMO if you want to use nix for your dev needs, that's fine, but pushing that down onto the wannabe users of your projects, prevents adoption greatly. nix downloaded over 8 GB of deps, including various stuff (one that stuck with me was gnome-vfs, just why?).

**Comment by arximboldi** [comment]
The CMake file still attempts to find the dependencies in more or less normal ways, so you can of course still install them manually. I'm sorry that Nix did not work for you.

**Comment by skrat** [comment]
@arximboldi maybe the sensible thing here would be to provide FindImmer.cmake and FindLager.cmake in the corresponding repos.

**Comment by arximboldi** [comment]
`FindImmer.cmake` and `FindLarger.cmake` are properly generated and installed with their respective `make install`.
